version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: 'src/main/docker/Dockerfile'
    container_name: veiculo-api
    hostname: 'veiculo-api'
    links: 
      - "postgresdb"
    depends_on: 
      - "postgresdb"
    ports:
      - "8080:8080"
  postgresdb:
    image: postgres:latest
    container_name: postgres-veiculo-api
    hostname: 'postgres-veiculo-api'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'veiculo-api'
    ports: 
      - "5432:5432"
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on: 
      - "postgresdb"
    command: postgresdb:5432
